#!/bin/sh

workfile="$TMPDIR/StandardKeyBinding.dict"
second_workfile="$workfile.tmp"
mapfile="$TMPDIR/key-code-map.txt"
cleanup() {
    rm "$workfile" "$mapfile"
    rm -f "$second_workfile"
}
trap cleanup EXIT

# copy system key bindings to the temp directory
cp /System/Library/Frameworks/AppKit.framework/Resources/StandardKeyBinding.dict "$workfile"

plutil -convert json "$workfile"
python3 -m json.tool "$workfile" > "$second_workfile"
cat "$second_workfile" > "$workfile"
rm "$second_workfile"

# taken from NSResponder.h
cat <<'EOF' > "$mapfile"
\\\uf700 UpArrow
\\\uf701 DownArrow
\\\uf702 LeftArrow
\\\uf703 RightArrow
\\\uf704 F1
\\\uf705 F2
\\\uf706 F3
\\\uf707 F4
\\\uf708 F5
\\\uf709 F6
\\\uf70a F7
\\\uf70b F8
\\\uf70c F9
\\\uf70d F10
\\\uf70e F11
\\\uf70f F12
\\\uf710 F13
\\\uf711 F14
\\\uf712 F15
\\\uf713 F16
\\\uf714 F17
\\\uf715 F18
\\\uf716 F19
\\\uf717 F20
\\\uf718 F21
\\\uf719 F22
\\\uf71a F23
\\\uf71b F24
\\\uf71c F25
\\\uf71d F26
\\\uf71e F27
\\\uf71f F28
\\\uf720 F29
\\\uf721 F30
\\\uf722 F31
\\\uf723 F32
\\\uf724 F33
\\\uf725 F34
\\\uf726 F35
\\\uf727 InsertFunctionKey
\\\uf728 DeleteFunctionKey
\\\uf729 HomeFunctionKey
\\\uf72a BeginFunctionKey
\\\uf72b EndFunctionKey
\\\uf72c PageUpFunctionKey
\\\uf72d PageDownFunctionKey
\\\uf72e PrintScreenFunctionKey
\\\uf72f ScrollLockFunctionKey
\\\uf730 PauseFunctionKey
\\\uf731 SysReqFunctionKey
\\\uf732 BreakFunctionKey
\\\uf733 ResetFunctionKey
\\\uf734 StopFunctionKey
\\\uf735 MenuFunctionKey
\\\uf736 UserFunctionKey
\\\uf737 SystemFunctionKey
\\\uf738 PrintFunctionKey
\\\uf739 ClearLineFunctionKey
\\\uf73a ClearDisplayFunctionKey
\\\uf73b InsertLineFunctionKey
\\\uf73c DeleteLineFunctionKey
\\\uf73d InsertCharFunctionKey
\\\uf73e DeleteCharFunctionKey
\\\uf73f PrevFunctionKey
\\\uf740 NextFunctionKey
\\\uf741 SelectFunctionKey
\\\uf742 ExecuteFunctionKey
\\\uf743 UndoFunctionKey
\\\uf744 RedoFunctionKey
\\\uf745 FindFunctionKey
\\\uf746 HelpFunctionKey
\\\uf747 ModeSwitchFunctionKey
EOF

cat <<'EOF' >> "$mapfile"
\\\u007f RegularDelete
\\\u0003 Return
\\\u0019 BackTab
\\\u001b Escape
EOF

while IFS= read -r line; do
    code=$(echo "$line" | awk '{ print $1 }')
    desc=$(echo "$line" | awk '{ print $2 }')
    sed -i '' "s/$code/$desc/g" "$workfile"
done < "$mapfile"

sed -i '' 's/\$/⇧/g' "$workfile"
sed -i '' 's/@/⌘/g' "$workfile"
sed -i '' 's/~/⌥/g' "$workfile"

cat "$workfile"
